import type { GradeName } from "./data";

export interface KihonPracticeItem {
    name: string;
    introducedAt: GradeName;
}

// A reviewable practice-oriented proposal assembled from the grading material.
// Keep this separate from the canonical source JSON until Sensei has reviewed it.
export const kaisokuAttacks: KihonPracticeItem[] = [
    { name: "me uchi", introducedAt: "6 kyū" },
    { name: "kinteki geri", introducedAt: "6 kyū" },
    { name: "furiko zuki", introducedAt: "6 kyū" },
    { name: "keri age", introducedAt: "6 kyū" },
    { name: "gedan zuki", introducedAt: "5 kyū" },
    { name: "shutō uchi", introducedAt: "5 kyū" },
    { name: "jō chū ni ren zuki", introducedAt: "5 kyū" },
    { name: "kumade zuki", introducedAt: "3 kyū" },
];

export const kaisokuDefences: KihonPracticeItem[] = [
    { name: "uwa uke", introducedAt: "6 kyū" },
    { name: "uchi uke", introducedAt: "6 kyū" },
    { name: "shita uke", introducedAt: "6 kyū" },
    { name: "uchi harai uke", introducedAt: "6 kyū" },
    { name: "soto uke", introducedAt: "4 kyū" },
    { name: "uchi age uke", introducedAt: "4 kyū" },
];

export const hidariMigiMaeTechniques: KihonPracticeItem[] = [
    { name: "jun zuki", introducedAt: "6 kyū" },
    { name: "gyaku zuki", introducedAt: "6 kyū" },
    { name: "jun geri", introducedAt: "6 kyū" },
    { name: "gyaku geri", introducedAt: "6 kyū" },
    { name: "sashikomi mawashi geri", introducedAt: "5 kyū" },
    { name: "sashikae sokuō geri", introducedAt: "4 kyū" },
    { name: "jō chū ni ren zuki", introducedAt: "3 kyū" },
    { name: "jō chū mawashi geri", introducedAt: "3 kyū" },
    { name: "ren geri", introducedAt: "1 kyū" },
    { name: "sashikae sokutō geri", introducedAt: "1 kyū" },
];

export const ukeCounterTechniques: KihonPracticeItem[] = [
    { name: "uchi uke zuki", introducedAt: "6 kyū" },
    { name: "uwa uke zuki", introducedAt: "6 kyū" },
    { name: "uwa uke geri", introducedAt: "5 kyū" },
    { name: "shita uke geri", introducedAt: "5 kyū" },
    { name: "shita uke jun geri", introducedAt: "5 kyū" },
    { name: "soto uke zuki", introducedAt: "4 kyū" },
    { name: "soto uke geri", introducedAt: "4 kyū" },
    { name: "uchi age zuki", introducedAt: "4 kyū" },
    { name: "uchi age geri", introducedAt: "4 kyū" },
    { name: "uchi uke geri", introducedAt: "3 kyū" },
    { name: "soto oshi uke zuki", introducedAt: "3 kyū" },
    { name: "uchi oshi uke zuki", introducedAt: "3 kyū" },
    { name: "jūji uke geri", introducedAt: "3 kyū" },
    { name: "soto oshi uke geri", introducedAt: "2 kyū" },
    { name: "uchi oshi uke geri", introducedAt: "2 kyū" },
    { name: "harai uke geri", introducedAt: "1 kyū" },
    { name: "shita uke zuki", introducedAt: "sandan" },
];

// These are examples explicitly named in Kamokuhyo, not combinations generated by the app.
export const koboTechniques: KihonPracticeItem[] = [
    { name: "jōdan zuki & ryūsui uke", introducedAt: "6 kyū" },
    { name: "jōdan zuki & uchi uke", introducedAt: "6 kyū" },
    { name: "jōdan zuki & soto uke", introducedAt: "4 kyū" },
    { name: "jōdan zuki & uchi age uke", introducedAt: "4 kyū" },
    { name: "furi zuki & soto oshi uke", introducedAt: "3 kyū" },
    { name: "furi zuki & uchi oshi uke", introducedAt: "3 kyū" },
    { name: "mawashi geri & uchi harai uke", introducedAt: "1 kyū" },
];

export const idoKoboTechniques: KihonPracticeItem[] = [
    { name: "jōdan zuki & uchi uke", introducedAt: "6 kyū" },
    { name: "chūdan zuki & shita uke", introducedAt: "6 kyū" },
    { name: "chūdan geri & uchi harai uke", introducedAt: "6 kyū" },
    { name: "shutō uchi & uwa uke", introducedAt: "6 kyū" },
    { name: "hiraki sagatte keri", introducedAt: "5 kyū" },
    { name: "hiraki sagatte uwa uke & keri", introducedAt: "5 kyū" },
    { name: "kagi zuki & uchi harai uke", introducedAt: "4 kyū" },
    { name: "mawashi geri & uchi harai uke", introducedAt: "4 kyū" },
    { name: "ni ren zuki & ren uke", introducedAt: "3 kyū" },
    { name: "mawashi geri & jūji uke", introducedAt: "3 kyū" },
    { name: "mawashi geri & gyaku zuki", introducedAt: "2 kyū" },
    { name: "ren: choku geri, mawashi geri, sokutō geri", introducedAt: "1 kyū" },
    { name: "ren zuki & ren uke", introducedAt: "1 kyū" },
    { name: "furi zuki & dan uke", introducedAt: "1 kyū" },
    { name: "ni ren zuki", introducedAt: "1 kyū" },
    { name: "san renkō", introducedAt: "1 kyū" },
    { name: "sashikae jun zuki & shita uke", introducedAt: "shodan" },
    { name: "jōdan zuki & han tenshin / gyaku tenshin", introducedAt: "shodan" },
    { name: "ren kōbō", introducedAt: "nidan" },
];
